### ISSUE TITLE
Klargjøre input/output

### ISSUE THREAD

**Issue by JoakimOL** [mjukvarelauget/trygt-baal#3]
Som dum forbruker vil jeg lett kunne se hvilke felt jeg kan putte noe i, og hvilke felt som vil inneholde resultatene

**Comment by Grimmbol** [comment]
mhm, er prioritet. Med litt flaks har kanskje Harvåd eller Aksel lyst til å hjelpe med UX

**Comment by haavarop** [comment]
Ikke når du skriver i ren Js/CSS/Html. Vi går ikke i 1.klasse heller

**Comment by Grimmbol** [comment]
Design /= implementasjon
